version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3002:3000"
        stdin_open: true
        volumes:
            - /app/node_modules
            - .:/app
    teste:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm","run","test"]